language: rust
cache: cargo
env:
  global:
  - PROJECT_NAME=rargs
matrix:
  include:
  - os: osx
    rust: stable
    env: TARGET=x86_64-apple-darwin
  - os: linux
    rust: stable
    env: TARGET=x86_64-unknown-linux-gnu
before_install:
- export PATH="$PATH:$HOME/.cargo/bin"
install:
- bash ci/install.sh
script:
- bash ci/script.sh
before_deploy:
- bash ci/before_deploy.sh
deploy:
  provider: releases
  file_glob: true
  file: "${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*"
  skip_cleanup: true
  on:
    condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
notifications:
  email:
    on_success: never
