[package]
name = "rargs"
version = "0.1.0"
authors = ["Jinzhou Zhang <lotabout@gmail.com>"]

[dependencies]
regex = "0.2.10"
structopt = { version = "0.2", default-features = false }
lazy_static = "1.0.0"
num_cpus = "1.0"
threadpool = "1.0"
